#! /bin/sh
feh --bg-scale /home/vaquita/Wallpapers/landscape2.jpg
pgrep -x sxhkd > /dev/null || sxhkd &
picom &

bspc monitor -d ス イ ル リ ラ ト 

bspc config border_width         2
bspc config active_border_color  "#cdd6f4"
bspc config normal_border_color  "#595959"
bspc config focused_border_color "#cdd6f4"
bspc config presel_feedback_color "#595959"


bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_mo:nocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

/home/vaquita/.config/polybar/launch.sh
